2025-07-05 22:13:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:13:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:13:53 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100660040>
    └ <Thread(Thread-7 (process_request_thread), started daemon 6288306176)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10065fd80>
    └ <Thread(Thread-7 (process_request_thread), started daemon 6288306176)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-7 (process_request_thread), started daemon 6288306176)>
    │    │        │    └ (<socket.socket fd=21, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57130)>, ('127.0.0.1', 57130))
    │    │        └ <Thread(Thread-7 (process_request_thread), started daemon 6288306176)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>>
    └ <Thread(Thread-7 (process_request_thread), started daemon 6288306176)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57130)
    │    │              └ <socket.socket fd=21, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57130)>
    │    └ <function BaseServer.finish_request at 0x100661da0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │    │                   │        └ ('127.0.0.1', 57130)
    │    │                   └ <socket.socket fd=21, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57130)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x101296ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107270cd0>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x10104c180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107270cd0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x107270cd0>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x107270cd0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b5bc0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10705fe00>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b5c60>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=21>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b5c60>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=21>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x101dbce00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x101dbc540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x101dbc4a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x1070279c0>, 'index': <function index at 0x1070454e0>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x101dbc720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1040004a0>
              └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1026ebc40>
               └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x1026e0360>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-05 22:14:05 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:05 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:05 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:05 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:12 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:12 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:12 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:12 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:13 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:13 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:13 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:13 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:50 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100660040>
    └ <Thread(Thread-17 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10065fd80>
    └ <Thread(Thread-17 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-17 (process_request_thread), started daemon 6356758528)>
    │    │        │    └ (<socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57381)>, ('127.0.0.1', 57381))
    │    │        └ <Thread(Thread-17 (process_request_thread), started daemon 6356758528)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>>
    └ <Thread(Thread-17 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57381)
    │    │              └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57381)>
    │    └ <function BaseServer.finish_request at 0x100661da0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │    │                   │        └ ('127.0.0.1', 57381)
    │    │                   └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57381)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x101296ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107217a50>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x10104c180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107217a50>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x107217a50>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x107217a50>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x10741d6c0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10705f6e0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10741e020>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10741e020>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x101dbce00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x101dbc540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x101dbc4a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x1070279c0>, 'index': <function index at 0x1070454e0>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x101dbc720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1040004a0>
              └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1026ebc40>
               └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x1026e0360>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-05 22:14:50 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:50 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:50 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:50 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:51 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100660040>
    └ <Thread(Thread-18 (process_request_thread), started daemon 6254653440)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10065fd80>
    └ <Thread(Thread-18 (process_request_thread), started daemon 6254653440)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-18 (process_request_thread), started daemon 6254653440)>
    │    │        │    └ (<socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57395)>, ('127.0.0.1', 57395))
    │    │        └ <Thread(Thread-18 (process_request_thread), started daemon 6254653440)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>>
    └ <Thread(Thread-18 (process_request_thread), started daemon 6254653440)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57395)
    │    │              └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57395)>
    │    └ <function BaseServer.finish_request at 0x100661da0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │    │                   │        └ ('127.0.0.1', 57395)
    │    │                   └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57395)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x101296ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10721a5d0>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x10104c180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10721a5d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10721a5d0>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10721a5d0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b58a0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10705f0f0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b6de0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b6de0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x101dbce00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x101dbc540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x101dbc4a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x1070279c0>, 'index': <function index at 0x1070454e0>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x101dbc720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1040004a0>
              └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1026ebc40>
               └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x1026e0360>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-05 22:14:51 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:51 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:51 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:51 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:52 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100660040>
    └ <Thread(Thread-19 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10065fd80>
    └ <Thread(Thread-19 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-19 (process_request_thread), started daemon 6356758528)>
    │    │        │    └ (<socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57406)>, ('127.0.0.1', 57406))
    │    │        └ <Thread(Thread-19 (process_request_thread), started daemon 6356758528)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>>
    └ <Thread(Thread-19 (process_request_thread), started daemon 6356758528)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57406)
    │    │              └ <socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57406)>
    │    └ <function BaseServer.finish_request at 0x100661da0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │    │                   │        └ ('127.0.0.1', 57406)
    │    │                   └ <socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57406)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x101296ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10721bb60>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x10104c180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10721bb60>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10721bb60>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10721bb60>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b6c00>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10705f0f0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072979c0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=28>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072979c0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=28>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x101dbce00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x101dbc540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x101dbc4a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x1070279c0>, 'index': <function index at 0x1070454e0>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x101dbc720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1040004a0>
              └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1026ebc40>
               └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x1026e0360>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-05 22:14:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:14:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:14:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:14:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:14:53 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100660040>
    └ <Thread(Thread-21 (process_request_thread), started daemon 6271479808)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10065fd80>
    └ <Thread(Thread-21 (process_request_thread), started daemon 6271479808)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-21 (process_request_thread), started daemon 6271479808)>
    │    │        │    └ (<socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57416)>, ('127.0.0.1', 57416))
    │    │        └ <Thread(Thread-21 (process_request_thread), started daemon 6271479808)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>>
    └ <Thread(Thread-21 (process_request_thread), started daemon 6271479808)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57416)
    │    │              └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57416)>
    │    └ <function BaseServer.finish_request at 0x100661da0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │    │                   │        └ ('127.0.0.1', 57416)
    │    │                   └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 57416)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x101296ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10725f770>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x10104c180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10725f770>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10725f770>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10703b4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10725f770>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x107296f20>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10705f0f0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072972e0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x107039fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072972e0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x101dbce00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x101dbc540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x101dbc4a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x1070279c0>, 'index': <function index at 0x1070454e0>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x101dbc720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1040004a0>
              └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1026ebc40>
               └ <exchanges.aster.Aster object at 0x1070407d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x1026e0360>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-05 22:15:03 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:15:03 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:15:03 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:15:03 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:15:09 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:15:09 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:15:09 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:15:09 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:15:12 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:15:12 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:15:12 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:15:12 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-05 22:15:13 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-05 22:15:13 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-05 22:15:13 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-05 22:15:13 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
